package src;

public enum Rooms {
    ACCOUNTING_HEAD_ROOM,
    ACCOUNTING_OPENSPACE,
    SALES_HEAD_ROOM,
    SALES_OPENSPACE,
    IT_SERVERS,
    IT_OPENSPACE,
    HR_HEAD_ROOM,
    HR_OPEN_SPACE,
    MARKETING_HEAD_ROOM,
    MARKETING_OPENSPACE,
}

